'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced

Public Partial Class Comisionxcobrador
	Private _tipo_socio As String 
	Public Overridable Property Tipo_socio As String
		Get
	        Return Me._tipo_socio
		End Get
		Set(ByVal value As String)
	        Me._tipo_socio = value
		End Set
	End Property
	
	Private _numero_recibo As Integer 
	Public Overridable Property Numero_recibo As Integer
		Get
	        Return Me._numero_recibo
		End Get
		Set(ByVal value As Integer)
	        Me._numero_recibo = value
		End Set
	End Property
	
	Private _nombre_socio As String 
	Public Overridable Property Nombre_socio As String
		Get
	        Return Me._nombre_socio
		End Get
		Set(ByVal value As String)
	        Me._nombre_socio = value
		End Set
	End Property
	
	Private _nombre_cobrador As String 
	Public Overridable Property Nombre_cobrador As String
		Get
	        Return Me._nombre_cobrador
		End Get
		Set(ByVal value As String)
	        Me._nombre_cobrador = value
		End Set
	End Property
	
	Private _monto_recibo As Decimal 
	Public Overridable Property Monto_recibo As Decimal
		Get
	        Return Me._monto_recibo
		End Get
		Set(ByVal value As Decimal)
	        Me._monto_recibo = value
		End Set
	End Property
	
	Private _mES_PAGO As String 
	Public Overridable Property MES_PAGO As String
		Get
	        Return Me._mES_PAGO
		End Get
		Set(ByVal value As String)
	        Me._mES_PAGO = value
		End Set
	End Property
	
	Private _fecha_recibo As Date 
	Public Overridable Property Fecha_recibo As Date
		Get
	        Return Me._fecha_recibo
		End Get
		Set(ByVal value As Date)
	        Me._fecha_recibo = value
		End Set
	End Property
	
	Private _comision As Decimal? 
	Public Overridable Property Comision As Decimal?
		Get
	        Return Me._comision
		End Get
		Set(ByVal value As Decimal?)
	        Me._comision = value
		End Set
	End Property
	
	Private _codigo_socio As String 
	Public Overridable Property Codigo_socio As String
		Get
	        Return Me._codigo_socio
		End Get
		Set(ByVal value As String)
	        Me._codigo_socio = value
		End Set
	End Property
	
	Private _año_pago As Integer 
	Public Overridable Property Año_pago As Integer
		Get
	        Return Me._año_pago
		End Get
		Set(ByVal value As Integer)
	        Me._año_pago = value
		End Set
	End Property
	
End Class
