'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ContextGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports scontrolpagos

Public Partial Class Entidades
	Inherits OpenAccessContext
	Implements IEntidadesUnitOfWork
	Private Shared connectionStringName As String = "cn"
	
	Private Shared backend As BackendConfiguration = GetBackendConfiguration()
			
	Private Shared metadataSource As MetadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq")
	
	Public Sub New()
		MyBase.New(connectionStringName, backend, metadataSource)
	End Sub
		
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, backend, metadataSource)
	End Sub
		
	Public Sub New(ByVal backendConfiguration As BackendConfiguration)
		MyBase.New(connectionStringName, backendConfiguration, metadataSource)
	End Sub
			
	Public Sub New(ByVal connection As String, ByVal metadataSource As MetadataSource)
		MyBase.New(connection, backend, metadataSource)
	End Sub
			
	Public Sub New(ByVal connection As String, ByVal backendConfiguration As BackendConfiguration, ByVal metadataSource As MetadataSource)
		MyBase.New(connection, backendConfiguration, metadataSource)
	End Sub
		
	Public ReadOnly Property Soc_tds_tipos_de_socios() As  IQueryable(Of Soc_tds_tipos_de_socios) Implements IEntidadesUnitOfWork.Soc_tds_tipos_de_socios
	    Get
			Return Me.GetAll(Of Soc_tds_tipos_de_socios)()
	    End Get
	End Property
	
	Public ReadOnly Property Soc_soc_socios() As  IQueryable(Of Soc_soc_socios) Implements IEntidadesUnitOfWork.Soc_soc_socios
	    Get
			Return Me.GetAll(Of Soc_soc_socios)()
	    End Get
	End Property
	
	Public ReadOnly Property Seg_uxr_usuarios_x_roles() As  IQueryable(Of Seg_uxr_usuarios_x_role) Implements IEntidadesUnitOfWork.Seg_uxr_usuarios_x_roles
	    Get
			Return Me.GetAll(Of Seg_uxr_usuarios_x_role)()
	    End Get
	End Property
	
	Public ReadOnly Property Seg_usu_usuarios() As  IQueryable(Of Seg_usu_usuarios) Implements IEntidadesUnitOfWork.Seg_usu_usuarios
	    Get
			Return Me.GetAll(Of Seg_usu_usuarios)()
	    End Get
	End Property
	
	Public ReadOnly Property Seg_rol_roles() As  IQueryable(Of Seg_rol_roles) Implements IEntidadesUnitOfWork.Seg_rol_roles
	    Get
			Return Me.GetAll(Of Seg_rol_roles)()
	    End Get
	End Property
	
	Public ReadOnly Property Seg_oxm_opciones_x_menus() As  IQueryable(Of Seg_oxm_opciones_x_menu) Implements IEntidadesUnitOfWork.Seg_oxm_opciones_x_menus
	    Get
			Return Me.GetAll(Of Seg_oxm_opciones_x_menu)()
	    End Get
	End Property
	
	Public ReadOnly Property Seg_opc_opciones() As  IQueryable(Of Seg_opc_opciones) Implements IEntidadesUnitOfWork.Seg_opc_opciones
	    Get
			Return Me.GetAll(Of Seg_opc_opciones)()
	    End Get
	End Property
	
	Public ReadOnly Property Seg_men_menus() As  IQueryable(Of Seg_men_menus) Implements IEntidadesUnitOfWork.Seg_men_menus
	    Get
			Return Me.GetAll(Of Seg_men_menus)()
	    End Get
	End Property
	
	Public ReadOnly Property Seg_axo_acciones_x_opcions() As  IQueryable(Of Seg_axo_acciones_x_opcion) Implements IEntidadesUnitOfWork.Seg_axo_acciones_x_opcions
	    Get
			Return Me.GetAll(Of Seg_axo_acciones_x_opcion)()
	    End Get
	End Property
	
	Public ReadOnly Property Seg_aro_autorizaciones_roles() As  IQueryable(Of Seg_aro_autorizaciones_role) Implements IEntidadesUnitOfWork.Seg_aro_autorizaciones_roles
	    Get
			Return Me.GetAll(Of Seg_aro_autorizaciones_role)()
	    End Get
	End Property
	
	Public ReadOnly Property Seg_acc_acciones() As  IQueryable(Of Seg_acc_acciones) Implements IEntidadesUnitOfWork.Seg_acc_acciones
	    Get
			Return Me.GetAll(Of Seg_acc_acciones)()
	    End Get
	End Property
	
	Public ReadOnly Property Pag_pag_pagos() As  IQueryable(Of Pag_pag_pagos) Implements IEntidadesUnitOfWork.Pag_pag_pagos
	    Get
			Return Me.GetAll(Of Pag_pag_pagos)()
	    End Get
	End Property
	
	Public ReadOnly Property Pag_cob_cobradores() As  IQueryable(Of Pag_cob_cobradores) Implements IEntidadesUnitOfWork.Pag_cob_cobradores
	    Get
			Return Me.GetAll(Of Pag_cob_cobradores)()
	    End Get
	End Property
	
	Public ReadOnly Property Grl_per_personas() As  IQueryable(Of Grl_per_personas) Implements IEntidadesUnitOfWork.Grl_per_personas
	    Get
			Return Me.GetAll(Of Grl_per_personas)()
	    End Get
	End Property
	
	Public ReadOnly Property Sociosmorosos() As  IQueryable(Of Sociosmorosos) Implements IEntidadesUnitOfWork.Sociosmorosos
	    Get
			Return Me.GetAll(Of Sociosmorosos)()
	    End Get
	End Property
	
	Public ReadOnly Property Controlpagos() As  IQueryable(Of Controlpagos) Implements IEntidadesUnitOfWork.Controlpagos
	    Get
			Return Me.GetAll(Of Controlpagos)()
	    End Get
	End Property
	
	Public ReadOnly Property Comisionxcobradors() As  IQueryable(Of Comisionxcobrador) Implements IEntidadesUnitOfWork.Comisionxcobradors
	    Get
			Return Me.GetAll(Of Comisionxcobrador)()
	    End Get
	End Property
	
	Public ReadOnly Property Pag_pag_pagos_hists() As  IQueryable(Of Pag_pag_pagos_hist) Implements IEntidadesUnitOfWork.Pag_pag_pagos_hists
	    Get
			Return Me.GetAll(Of Pag_pag_pagos_hist)()
	    End Get
	End Property
	
	Public ReadOnly Property Tar_tar_tarjetas() As  IQueryable(Of Tar_tar_tarjetas) Implements IEntidadesUnitOfWork.Tar_tar_tarjetas
	    Get
			Return Me.GetAll(Of Tar_tar_tarjetas)()
	    End Get
	End Property
	
	Public Sub Reroute_Add(entity As Object) Implements IUnitOfWork.Add
		Me.Add(entity)
	End Sub
	
	Public Sub Reroute_ClearChanges() Implements IUnitOfWork.ClearChanges
		Me.ClearChanges()
	End Sub
	
	Public Sub Reroute_Delete(entity As Object) Implements IUnitOfWork.Delete
		Me.Delete(entity)
	End Sub
	
	Public Function Reroute_GetAll(Of T)() As IQueryable(Of T) Implements IUnitOfWork.GetAll
		Return Me.GetAll(Of T)()
	End Function
	
	Public Function Reroute_GetObjectByKey(Of T)(key As Telerik.OpenAccess.ObjectKey) As T Implements IUnitOfWork.GetObjectByKey
		Return CType(Me.GetObjectByKey(key), T)
	End Function
	
	Public Sub Reroute_SaveChanges() Implements IUnitOfWork.SaveChanges
		Me.SaveChanges()
	End Sub
	Public Shared Function GetBackendConfiguration() As BackendConfiguration
		Dim backend As BackendConfiguration = New BackendConfiguration()
		backend.Backend = "MySql"
		backend.ProviderName = "MySql.Data.MySqlClient"
		
		CustomizeBackendConfiguration(backend)
	
		Return backend
	End Function
	
	''' <summary>
	''' Allows you to customize the BackendConfiguration of Entidades.
	''' </summary>
	''' <param name="config">The BackendConfiguration of Entidades.</param>
	Private Shared Partial Sub CustomizeBackendConfiguration(ByRef config As BackendConfiguration)
	End Sub
	
End Class

Public Interface IEntidadesUnitOfWork
	Inherits IUnitOfWork
	ReadOnly Property Soc_tds_tipos_de_socios() As IQueryable(Of Soc_tds_tipos_de_socios)
	ReadOnly Property Soc_soc_socios() As IQueryable(Of Soc_soc_socios)
	ReadOnly Property Seg_uxr_usuarios_x_roles() As IQueryable(Of Seg_uxr_usuarios_x_role)
	ReadOnly Property Seg_usu_usuarios() As IQueryable(Of Seg_usu_usuarios)
	ReadOnly Property Seg_rol_roles() As IQueryable(Of Seg_rol_roles)
	ReadOnly Property Seg_oxm_opciones_x_menus() As IQueryable(Of Seg_oxm_opciones_x_menu)
	ReadOnly Property Seg_opc_opciones() As IQueryable(Of Seg_opc_opciones)
	ReadOnly Property Seg_men_menus() As IQueryable(Of Seg_men_menus)
	ReadOnly Property Seg_axo_acciones_x_opcions() As IQueryable(Of Seg_axo_acciones_x_opcion)
	ReadOnly Property Seg_aro_autorizaciones_roles() As IQueryable(Of Seg_aro_autorizaciones_role)
	ReadOnly Property Seg_acc_acciones() As IQueryable(Of Seg_acc_acciones)
	ReadOnly Property Pag_pag_pagos() As IQueryable(Of Pag_pag_pagos)
	ReadOnly Property Pag_cob_cobradores() As IQueryable(Of Pag_cob_cobradores)
	ReadOnly Property Grl_per_personas() As IQueryable(Of Grl_per_personas)
	ReadOnly Property Sociosmorosos() As IQueryable(Of Sociosmorosos)
	ReadOnly Property Controlpagos() As IQueryable(Of Controlpagos)
	ReadOnly Property Comisionxcobradors() As IQueryable(Of Comisionxcobrador)
	ReadOnly Property Pag_pag_pagos_hists() As IQueryable(Of Pag_pag_pagos_hist)
	ReadOnly Property Tar_tar_tarjetas() As IQueryable(Of Tar_tar_tarjetas)
End Interface
