'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports scontrolpagos

Public Partial Class Grl_per_personas
	Private _per_codigo As Integer 
	Public Overridable Property Per_codigo As Integer
		Get
	        Return Me._per_codigo
		End Get
		Set(ByVal value As Integer)
	        Me._per_codigo = value
		End Set
	End Property
	
	Private _per_primer_nombre As String 
	Public Overridable Property Per_primer_nombre As String
		Get
	        Return Me._per_primer_nombre
		End Get
		Set(ByVal value As String)
	        Me._per_primer_nombre = value
		End Set
	End Property
	
	Private _per_segundo_nombre As String 
	Public Overridable Property Per_segundo_nombre As String
		Get
	        Return Me._per_segundo_nombre
		End Get
		Set(ByVal value As String)
	        Me._per_segundo_nombre = value
		End Set
	End Property
	
	Private _per_primer_apellido As String 
	Public Overridable Property Per_primer_apellido As String
		Get
	        Return Me._per_primer_apellido
		End Get
		Set(ByVal value As String)
	        Me._per_primer_apellido = value
		End Set
	End Property
	
	Private _per_segundo_apellido As String 
	Public Overridable Property Per_segundo_apellido As String
		Get
	        Return Me._per_segundo_apellido
		End Get
		Set(ByVal value As String)
	        Me._per_segundo_apellido = value
		End Set
	End Property
	
	Private _per_apellido_casada As String 
	Public Overridable Property Per_apellido_casada As String
		Get
	        Return Me._per_apellido_casada
		End Get
		Set(ByVal value As String)
	        Me._per_apellido_casada = value
		End Set
	End Property
	
	Private _per_nombre_completo As String 
	Public Overridable Property Per_nombre_completo As String
		Get
	        Return Me._per_nombre_completo
		End Get
		Set(ByVal value As String)
	        Me._per_nombre_completo = value
		End Set
	End Property
	
	Private _per_DPI As String 
	Public Overridable Property Per_DPI As String
		Get
	        Return Me._per_DPI
		End Get
		Set(ByVal value As String)
	        Me._per_DPI = value
		End Set
	End Property
	
	Private _per_cedula As String 
	Public Overridable Property Per_cedula As String
		Get
	        Return Me._per_cedula
		End Get
		Set(ByVal value As String)
	        Me._per_cedula = value
		End Set
	End Property
	
	Private _per_departamento_extendida As String 
	Public Overridable Property Per_departamento_extendida As String
		Get
	        Return Me._per_departamento_extendida
		End Get
		Set(ByVal value As String)
	        Me._per_departamento_extendida = value
		End Set
	End Property
	
	Private _per_municipio_extendida As String 
	Public Overridable Property Per_municipio_extendida As String
		Get
	        Return Me._per_municipio_extendida
		End Get
		Set(ByVal value As String)
	        Me._per_municipio_extendida = value
		End Set
	End Property
	
	Private _per_direccion_cobro As String 
	Public Overridable Property Per_direccion_cobro As String
		Get
	        Return Me._per_direccion_cobro
		End Get
		Set(ByVal value As String)
	        Me._per_direccion_cobro = value
		End Set
	End Property
	
	Private _per_telefonos As String 
	Public Overridable Property Per_telefonos As String
		Get
	        Return Me._per_telefonos
		End Get
		Set(ByVal value As String)
	        Me._per_telefonos = value
		End Set
	End Property
	
	Private _per_celulares As String 
	Public Overridable Property Per_celulares As String
		Get
	        Return Me._per_celulares
		End Get
		Set(ByVal value As String)
	        Me._per_celulares = value
		End Set
	End Property
	
	Private _per_correo_electronico As String 
	Public Overridable Property Per_correo_electronico As String
		Get
	        Return Me._per_correo_electronico
		End Get
		Set(ByVal value As String)
	        Me._per_correo_electronico = value
		End Set
	End Property
	
	Private _per_fecha_nacimiento As Date 
	Public Overridable Property Per_fecha_nacimiento As Date
		Get
	        Return Me._per_fecha_nacimiento
		End Get
		Set(ByVal value As Date)
	        Me._per_fecha_nacimiento = value
		End Set
	End Property
	
	Private _per_foto As Byte() 
	Public Overridable Property Per_foto As Byte()
		Get
	        Return Me._per_foto
		End Get
		Set(ByVal value As Byte())
	        Me._per_foto = value
		End Set
	End Property
	
	Private _per_estado As String 
	Public Overridable Property Per_estado As String
		Get
	        Return Me._per_estado
		End Get
		Set(ByVal value As String)
	        Me._per_estado = value
		End Set
	End Property
	
	Private _soc_soc_socios As IList(Of Soc_soc_socios)  = new List(Of Soc_soc_socios)
	Private ReadOnly Property Soc_soc_socios As IList(Of Soc_soc_socios)
		Get
	        Return Me._soc_soc_socios
		End Get
	End Property
	
	Private _pag_cob_cobradores As IList(Of Pag_cob_cobradores)  = new List(Of Pag_cob_cobradores)
	Private ReadOnly Property Pag_cob_cobradores As IList(Of Pag_cob_cobradores)
		Get
	        Return Me._pag_cob_cobradores
		End Get
	End Property
	
End Class
