'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced

Public Partial Class Pag_pag_pagos_hist
	Private _pag_correlativo As Integer 
	Public Overridable Property Pag_correlativo As Integer
		Get
	        Return Me._pag_correlativo
		End Get
		Set(ByVal value As Integer)
	        Me._pag_correlativo = value
		End Set
	End Property
	
	Private _pag_codigo As Integer? 
	Public Overridable Property Pag_codigo As Integer?
		Get
	        Return Me._pag_codigo
		End Get
		Set(ByVal value As Integer?)
	        Me._pag_codigo = value
		End Set
	End Property
	
	Private _pag_codsoc As Integer? 
	Public Overridable Property Pag_codsoc As Integer?
		Get
	        Return Me._pag_codsoc
		End Get
		Set(ByVal value As Integer?)
	        Me._pag_codsoc = value
		End Set
	End Property
	
	Private _pag_codcob As Integer? 
	Public Overridable Property Pag_codcob As Integer?
		Get
	        Return Me._pag_codcob
		End Get
		Set(ByVal value As Integer?)
	        Me._pag_codcob = value
		End Set
	End Property
	
	Private _pag_monto As Decimal? 
	Public Overridable Property Pag_monto As Decimal?
		Get
	        Return Me._pag_monto
		End Get
		Set(ByVal value As Decimal?)
	        Me._pag_monto = value
		End Set
	End Property
	
	Private _pag_mes As Integer? 
	Public Overridable Property Pag_mes As Integer?
		Get
	        Return Me._pag_mes
		End Get
		Set(ByVal value As Integer?)
	        Me._pag_mes = value
		End Set
	End Property
	
	Private _pag_año As Integer? 
	Public Overridable Property Pag_año As Integer?
		Get
	        Return Me._pag_año
		End Get
		Set(ByVal value As Integer?)
	        Me._pag_año = value
		End Set
	End Property
	
	Private _pag_numero_recibo As Integer? 
	Public Overridable Property Pag_numero_recibo As Integer?
		Get
	        Return Me._pag_numero_recibo
		End Get
		Set(ByVal value As Integer?)
	        Me._pag_numero_recibo = value
		End Set
	End Property
	
	Private _pag_fecha_recibido As Date? 
	Public Overridable Property Pag_fecha_recibido As Date?
		Get
	        Return Me._pag_fecha_recibido
		End Get
		Set(ByVal value As Date?)
	        Me._pag_fecha_recibido = value
		End Set
	End Property
	
	Private _pag_observaciones As String 
	Public Overridable Property Pag_observaciones As String
		Get
	        Return Me._pag_observaciones
		End Get
		Set(ByVal value As String)
	        Me._pag_observaciones = value
		End Set
	End Property
	
	Private _pag_usuario_grabacion As String 
	Public Overridable Property Pag_usuario_grabacion As String
		Get
	        Return Me._pag_usuario_grabacion
		End Get
		Set(ByVal value As String)
	        Me._pag_usuario_grabacion = value
		End Set
	End Property
	
	Private _pag_fecha_grabacion As Date? 
	Public Overridable Property Pag_fecha_grabacion As Date?
		Get
	        Return Me._pag_fecha_grabacion
		End Get
		Set(ByVal value As Date?)
	        Me._pag_fecha_grabacion = value
		End Set
	End Property
	
	Private _pag_usuario_modificacion As String 
	Public Overridable Property Pag_usuario_modificacion As String
		Get
	        Return Me._pag_usuario_modificacion
		End Get
		Set(ByVal value As String)
	        Me._pag_usuario_modificacion = value
		End Set
	End Property
	
	Private _pag_fecha_modificacion As Date? 
	Public Overridable Property Pag_fecha_modificacion As Date?
		Get
	        Return Me._pag_fecha_modificacion
		End Get
		Set(ByVal value As Date?)
	        Me._pag_fecha_modificacion = value
		End Set
	End Property
	
	Private _pag_descripcion As String 
	Public Overridable Property Pag_descripcion As String
		Get
	        Return Me._pag_descripcion
		End Get
		Set(ByVal value As String)
	        Me._pag_descripcion = value
		End Set
	End Property
	
End Class
