'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports scontrolpagos

Public Partial Class Pag_cob_cobradores
	Private _cob_codigo As Integer 
	Public Overridable Property Cob_codigo As Integer
		Get
	        Return Me._cob_codigo
		End Get
		Set(ByVal value As Integer)
	        Me._cob_codigo = value
		End Set
	End Property
	
	Private _cob_codper As Integer 
	Public Overridable Property Cob_codper As Integer
		Get
	        Return Me._cob_codper
		End Get
		Set(ByVal value As Integer)
	        Me._cob_codper = value
		End Set
	End Property
	
	Private _cob_porcentaje_comision As Decimal? 
	Public Overridable Property Cob_porcentaje_comision As Decimal?
		Get
	        Return Me._cob_porcentaje_comision
		End Get
		Set(ByVal value As Decimal?)
	        Me._cob_porcentaje_comision = value
		End Set
	End Property
	
	Private _grl_per_personas As Grl_per_personas 
	Private Property Grl_per_personas As Grl_per_personas
		Get
	        Return Me._grl_per_personas
		End Get
		Set(ByVal value As Grl_per_personas)
	        Me._grl_per_personas = value
		End Set
	End Property
	
	Private _pag_pag_pagos As IList(Of Pag_pag_pagos)  = new List(Of Pag_pag_pagos)
	Private ReadOnly Property Pag_pag_pagos As IList(Of Pag_pag_pagos)
		Get
	        Return Me._pag_pag_pagos
		End Get
	End Property
	
End Class
