'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports scontrolpagos

Public Partial Class Seg_rol_roles
	Private _rol_codigo As Integer 
	Public Overridable Property Rol_codigo As Integer
		Get
	        Return Me._rol_codigo
		End Get
		Set(ByVal value As Integer)
	        Me._rol_codigo = value
		End Set
	End Property
	
	Private _rol_descripcion As String 
	Public Overridable Property Rol_descripcion As String
		Get
	        Return Me._rol_descripcion
		End Get
		Set(ByVal value As String)
	        Me._rol_descripcion = value
		End Set
	End Property
	
	Private _seg_uxr_usuarios_x_roles As IList(Of Seg_uxr_usuarios_x_role)  = new List(Of Seg_uxr_usuarios_x_role)
	Private ReadOnly Property Seg_uxr_usuarios_x_roles As IList(Of Seg_uxr_usuarios_x_role)
		Get
	        Return Me._seg_uxr_usuarios_x_roles
		End Get
	End Property
	
	Private _seg_aro_autorizaciones_roles As IList(Of Seg_aro_autorizaciones_role)  = new List(Of Seg_aro_autorizaciones_role)
	Private ReadOnly Property Seg_aro_autorizaciones_roles As IList(Of Seg_aro_autorizaciones_role)
		Get
	        Return Me._seg_aro_autorizaciones_roles
		End Get
	End Property
	
End Class
