'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports scontrolpagos

Public Partial Class Seg_usu_usuarios
	Private _usu_codigo As Integer 
	Public Overridable Property Usu_codigo As Integer
		Get
	        Return Me._usu_codigo
		End Get
		Set(ByVal value As Integer)
	        Me._usu_codigo = value
		End Set
	End Property
	
	Private _usu_nombre As String 
	Public Overridable Property Usu_nombre As String
		Get
	        Return Me._usu_nombre
		End Get
		Set(ByVal value As String)
	        Me._usu_nombre = value
		End Set
	End Property
	
	Private _usu_usuario As String 
	Public Overridable Property Usu_usuario As String
		Get
	        Return Me._usu_usuario
		End Get
		Set(ByVal value As String)
	        Me._usu_usuario = value
		End Set
	End Property
	
	Private _usu_password As String 
	Public Overridable Property Usu_password As String
		Get
	        Return Me._usu_password
		End Get
		Set(ByVal value As String)
	        Me._usu_password = value
		End Set
	End Property
	
	Private _usu_estado As String 
	Public Overridable Property Usu_estado As String
		Get
	        Return Me._usu_estado
		End Get
		Set(ByVal value As String)
	        Me._usu_estado = value
		End Set
	End Property
	
	Private _usu_usuario_modificacion As String 
	Public Overridable Property Usu_usuario_modificacion As String
		Get
	        Return Me._usu_usuario_modificacion
		End Get
		Set(ByVal value As String)
	        Me._usu_usuario_modificacion = value
		End Set
	End Property
	
	Private _usu_usuario_grabacion As String 
	Public Overridable Property Usu_usuario_grabacion As String
		Get
	        Return Me._usu_usuario_grabacion
		End Get
		Set(ByVal value As String)
	        Me._usu_usuario_grabacion = value
		End Set
	End Property
	
	Private _usu_fecha_modificacion As Date? 
	Public Overridable Property Usu_fecha_modificacion As Date?
		Get
	        Return Me._usu_fecha_modificacion
		End Get
		Set(ByVal value As Date?)
	        Me._usu_fecha_modificacion = value
		End Set
	End Property
	
	Private _usu_fecha_grabacion As Date? 
	Public Overridable Property Usu_fecha_grabacion As Date?
		Get
	        Return Me._usu_fecha_grabacion
		End Get
		Set(ByVal value As Date?)
	        Me._usu_fecha_grabacion = value
		End Set
	End Property
	
	Private _usu_codper As Integer? 
	Public Overridable Property Usu_codper As Integer?
		Get
	        Return Me._usu_codper
		End Get
		Set(ByVal value As Integer?)
	        Me._usu_codper = value
		End Set
	End Property
	
	Private _seg_uxr_usuarios_x_roles As Seg_uxr_usuarios_x_role 
	Private Property Seg_uxr_usuarios_x_roles As Seg_uxr_usuarios_x_role
		Get
	        Return Me._seg_uxr_usuarios_x_roles
		End Get
		Set(ByVal value As Seg_uxr_usuarios_x_role)
	        Me._seg_uxr_usuarios_x_roles = value
		End Set
	End Property
	
End Class
