'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports scontrolpagos

Public Partial Class Seg_acc_acciones
	Private _acc_codigo As Integer 
	Public Overridable Property Acc_codigo As Integer
		Get
	        Return Me._acc_codigo
		End Get
		Set(ByVal value As Integer)
	        Me._acc_codigo = value
		End Set
	End Property
	
	Private _acc_descripcion As String 
	Public Overridable Property Acc_descripcion As String
		Get
	        Return Me._acc_descripcion
		End Get
		Set(ByVal value As String)
	        Me._acc_descripcion = value
		End Set
	End Property
	
	Private _seg_axo_acciones_x_opcions As IList(Of Seg_axo_acciones_x_opcion)  = new List(Of Seg_axo_acciones_x_opcion)
	Private ReadOnly Property Seg_axo_acciones_x_opcions As IList(Of Seg_axo_acciones_x_opcion)
		Get
	        Return Me._seg_axo_acciones_x_opcions
		End Get
	End Property
	
End Class
