'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports scontrolpagos

Public Partial Class Seg_oxm_opciones_x_menu
	Private _oxm_codmen As Integer 
	Public Overridable Property Oxm_codmen As Integer
		Get
	        Return Me._oxm_codmen
		End Get
		Set(ByVal value As Integer)
	        Me._oxm_codmen = value
		End Set
	End Property
	
	Private _oxm_codopc As Integer 
	Public Overridable Property Oxm_codopc As Integer
		Get
	        Return Me._oxm_codopc
		End Get
		Set(ByVal value As Integer)
	        Me._oxm_codopc = value
		End Set
	End Property
	
	Private _oxm_orden As Integer 
	Public Overridable Property Oxm_orden As Integer
		Get
	        Return Me._oxm_orden
		End Get
		Set(ByVal value As Integer)
	        Me._oxm_orden = value
		End Set
	End Property
	
	Private _seg_men_menus As Seg_men_menus 
	Private Property Seg_men_menus As Seg_men_menus
		Get
	        Return Me._seg_men_menus
		End Get
		Set(ByVal value As Seg_men_menus)
	        Me._seg_men_menus = value
		End Set
	End Property
	
	Private _seg_opc_opciones As Seg_opc_opciones 
	Private Property Seg_opc_opciones As Seg_opc_opciones
		Get
	        Return Me._seg_opc_opciones
		End Get
		Set(ByVal value As Seg_opc_opciones)
	        Me._seg_opc_opciones = value
		End Set
	End Property
	
End Class
