'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports scontrolpagos

Public Partial Class Seg_axo_acciones_x_opcion
	Private _axo_codopc As Integer 
	Public Overridable Property Axo_codopc As Integer
		Get
	        Return Me._axo_codopc
		End Get
		Set(ByVal value As Integer)
	        Me._axo_codopc = value
		End Set
	End Property
	
	Private _axo_codacc As Integer 
	Public Overridable Property Axo_codacc As Integer
		Get
	        Return Me._axo_codacc
		End Get
		Set(ByVal value As Integer)
	        Me._axo_codacc = value
		End Set
	End Property
	
	Private _seg_opc_opciones As Seg_opc_opciones 
	Private Property Seg_opc_opciones As Seg_opc_opciones
		Get
	        Return Me._seg_opc_opciones
		End Get
		Set(ByVal value As Seg_opc_opciones)
	        Me._seg_opc_opciones = value
		End Set
	End Property
	
	Private _seg_acc_acciones As Seg_acc_acciones 
	Private Property Seg_acc_acciones As Seg_acc_acciones
		Get
	        Return Me._seg_acc_acciones
		End Get
		Set(ByVal value As Seg_acc_acciones)
	        Me._seg_acc_acciones = value
		End Set
	End Property
	
	Private _seg_aro_autorizaciones_roles As IList(Of Seg_aro_autorizaciones_role)  = new List(Of Seg_aro_autorizaciones_role)
	Private ReadOnly Property Seg_aro_autorizaciones_roles As IList(Of Seg_aro_autorizaciones_role)
		Get
	        Return Me._seg_aro_autorizaciones_roles
		End Get
	End Property
	
End Class
