'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports scontrolpagos

Public Partial Class Seg_uxr_usuarios_x_role
	Private _uxr_codrol As Integer 
	Public Overridable Property Uxr_codrol As Integer
		Get
	        Return Me._uxr_codrol
		End Get
		Set(ByVal value As Integer)
	        Me._uxr_codrol = value
		End Set
	End Property
	
	Private _uxr_codusu As Integer 
	Public Overridable Property Uxr_codusu As Integer
		Get
	        Return Me._uxr_codusu
		End Get
		Set(ByVal value As Integer)
	        Me._uxr_codusu = value
		End Set
	End Property
	
	Private _seg_rol_roles As Seg_rol_roles 
	Private Property Seg_rol_roles As Seg_rol_roles
		Get
	        Return Me._seg_rol_roles
		End Get
		Set(ByVal value As Seg_rol_roles)
	        Me._seg_rol_roles = value
		End Set
	End Property
	
	Private _seg_usu_usuarios As Seg_usu_usuarios 
	Private Property Seg_usu_usuarios As Seg_usu_usuarios
		Get
	        Return Me._seg_usu_usuarios
		End Get
		Set(ByVal value As Seg_usu_usuarios)
	        Me._seg_usu_usuarios = value
		End Set
	End Property
	
End Class
