'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports scontrolpagos

Public Partial Class Soc_soc_socios
	Private _soc_codigo As Integer 
	Public Overridable Property Soc_codigo As Integer
		Get
	        Return Me._soc_codigo
		End Get
		Set(ByVal value As Integer)
	        Me._soc_codigo = value
		End Set
	End Property
	
	Private _soc_codper As Integer 
	Public Overridable Property Soc_codper As Integer
		Get
	        Return Me._soc_codper
		End Get
		Set(ByVal value As Integer)
	        Me._soc_codper = value
		End Set
	End Property
	
	Private _soc_codtds As Integer 
	Public Overridable Property Soc_codtds As Integer
		Get
	        Return Me._soc_codtds
		End Get
		Set(ByVal value As Integer)
	        Me._soc_codtds = value
		End Set
	End Property
	
	Private _soc_correlativo As Integer 
	Public Overridable Property Soc_correlativo As Integer
		Get
	        Return Me._soc_correlativo
		End Get
		Set(ByVal value As Integer)
	        Me._soc_correlativo = value
		End Set
	End Property
	
	Private _soc_codigo_armado As String 
	Public Overridable Property Soc_codigo_armado As String
		Get
	        Return Me._soc_codigo_armado
		End Get
		Set(ByVal value As String)
	        Me._soc_codigo_armado = value
		End Set
	End Property
	
	Private _soc_estado As String 
	Public Overridable Property Soc_estado As String
		Get
	        Return Me._soc_estado
		End Get
		Set(ByVal value As String)
	        Me._soc_estado = value
		End Set
	End Property
	
	Private _soc_fecha_inicio_socio As Date? 
	Public Overridable Property Soc_fecha_inicio_socio As Date?
		Get
	        Return Me._soc_fecha_inicio_socio
		End Get
		Set(ByVal value As Date?)
	        Me._soc_fecha_inicio_socio = value
		End Set
	End Property
	
	Private _soc_fecha_fin_socio As Date? 
	Public Overridable Property Soc_fecha_fin_socio As Date?
		Get
	        Return Me._soc_fecha_fin_socio
		End Get
		Set(ByVal value As Date?)
	        Me._soc_fecha_fin_socio = value
		End Set
	End Property
	
	Private _soc_motivo_fin_socio As String 
	Public Overridable Property Soc_motivo_fin_socio As String
		Get
	        Return Me._soc_motivo_fin_socio
		End Get
		Set(ByVal value As String)
	        Me._soc_motivo_fin_socio = value
		End Set
	End Property
	
	Private _soc_usuario_modificacion As String 
	Public Overridable Property Soc_usuario_modificacion As String
		Get
	        Return Me._soc_usuario_modificacion
		End Get
		Set(ByVal value As String)
	        Me._soc_usuario_modificacion = value
		End Set
	End Property
	
	Private _soc_usuario_grabacion As String 
	Public Overridable Property Soc_usuario_grabacion As String
		Get
	        Return Me._soc_usuario_grabacion
		End Get
		Set(ByVal value As String)
	        Me._soc_usuario_grabacion = value
		End Set
	End Property
	
	Private _soc_UID_4 As Short? 
	Public Overridable Property Soc_UID_4 As Short?
		Get
	        Return Me._soc_UID_4
		End Get
		Set(ByVal value As Short?)
	        Me._soc_UID_4 = value
		End Set
	End Property
	
	Private _soc_UID_3 As Short? 
	Public Overridable Property Soc_UID_3 As Short?
		Get
	        Return Me._soc_UID_3
		End Get
		Set(ByVal value As Short?)
	        Me._soc_UID_3 = value
		End Set
	End Property
	
	Private _soc_UID_2 As Short? 
	Public Overridable Property Soc_UID_2 As Short?
		Get
	        Return Me._soc_UID_2
		End Get
		Set(ByVal value As Short?)
	        Me._soc_UID_2 = value
		End Set
	End Property
	
	Private _soc_UID_1 As Short? 
	Public Overridable Property Soc_UID_1 As Short?
		Get
	        Return Me._soc_UID_1
		End Get
		Set(ByVal value As Short?)
	        Me._soc_UID_1 = value
		End Set
	End Property
	
	Private _soc_fecha_modificacion As Date? 
	Public Overridable Property Soc_fecha_modificacion As Date?
		Get
	        Return Me._soc_fecha_modificacion
		End Get
		Set(ByVal value As Date?)
	        Me._soc_fecha_modificacion = value
		End Set
	End Property
	
	Private _soc_fecha_grabacion As Date? 
	Public Overridable Property Soc_fecha_grabacion As Date?
		Get
	        Return Me._soc_fecha_grabacion
		End Get
		Set(ByVal value As Date?)
	        Me._soc_fecha_grabacion = value
		End Set
	End Property
	
	Private _grl_per_personas As Grl_per_personas 
	Private Property Grl_per_personas As Grl_per_personas
		Get
	        Return Me._grl_per_personas
		End Get
		Set(ByVal value As Grl_per_personas)
	        Me._grl_per_personas = value
		End Set
	End Property
	
	Private _soc_tds_tipos_de_socios As Soc_tds_tipos_de_socios 
	Private Property Soc_tds_tipos_de_socios As Soc_tds_tipos_de_socios
		Get
	        Return Me._soc_tds_tipos_de_socios
		End Get
		Set(ByVal value As Soc_tds_tipos_de_socios)
	        Me._soc_tds_tipos_de_socios = value
		End Set
	End Property
	
	Private _pag_pag_pagos As IList(Of Pag_pag_pagos)  = new List(Of Pag_pag_pagos)
	Private ReadOnly Property Pag_pag_pagos As IList(Of Pag_pag_pagos)
		Get
	        Return Me._pag_pag_pagos
		End Get
	End Property
	
End Class
