'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced

Public Partial Class Sociosmorosos
	Private _tipo_socio As Integer 
	Public Overridable Property Tipo_socio As Integer
		Get
	        Return Me._tipo_socio
		End Get
		Set(ByVal value As Integer)
	        Me._tipo_socio = value
		End Set
	End Property
	
	Private _nombre_socio As String 
	Public Overridable Property Nombre_socio As String
		Get
	        Return Me._nombre_socio
		End Get
		Set(ByVal value As String)
	        Me._nombre_socio = value
		End Set
	End Property
	
	Private _mes_pago As Integer 
	Public Overridable Property Mes_pago As Integer
		Get
	        Return Me._mes_pago
		End Get
		Set(ByVal value As Integer)
	        Me._mes_pago = value
		End Set
	End Property
	
	Private _codigo_socio As String 
	Public Overridable Property Codigo_socio As String
		Get
	        Return Me._codigo_socio
		End Get
		Set(ByVal value As String)
	        Me._codigo_socio = value
		End Set
	End Property
	
	Private _anio_pago As Integer 
	Public Overridable Property Anio_pago As Integer
		Get
	        Return Me._anio_pago
		End Get
		Set(ByVal value As Integer)
	        Me._anio_pago = value
		End Set
	End Property
	
End Class
