'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced

Public Partial Class Tar_tar_tarjetas
	Private _tar_codigo As Integer 
	Public Overridable Property Tar_codigo As Integer
		Get
	        Return Me._tar_codigo
		End Get
		Set(ByVal value As Integer)
	        Me._tar_codigo = value
		End Set
	End Property
	
	Private _tar_tipo As Integer 
	Public Overridable Property Tar_tipo As Integer
		Get
	        Return Me._tar_tipo
		End Get
		Set(ByVal value As Integer)
	        Me._tar_tipo = value
		End Set
	End Property
	
	Private _tar_nombre As String 
	Public Overridable Property Tar_nombre As String
		Get
	        Return Me._tar_nombre
		End Get
		Set(ByVal value As String)
	        Me._tar_nombre = value
		End Set
	End Property
	
	Private _tar_numero As Integer 
	Public Overridable Property Tar_numero As Integer
		Get
	        Return Me._tar_numero
		End Get
		Set(ByVal value As Integer)
	        Me._tar_numero = value
		End Set
	End Property
	
	Private _tar_fecha_hora_ingreso As Date? 
	Public Overridable Property Tar_fecha_hora_ingreso As Date?
		Get
	        Return Me._tar_fecha_hora_ingreso
		End Get
		Set(ByVal value As Date?)
	        Me._tar_fecha_hora_ingreso = value
		End Set
	End Property
	
	Private _tar_fecha_hora_activacion As Date? 
	Public Overridable Property Tar_fecha_hora_activacion As Date?
		Get
	        Return Me._tar_fecha_hora_activacion
		End Get
		Set(ByVal value As Date?)
	        Me._tar_fecha_hora_activacion = value
		End Set
	End Property
	
	Private _tar_fecha_hora_inicio_vigencia As Date? 
	Public Overridable Property Tar_fecha_hora_inicio_vigencia As Date?
		Get
	        Return Me._tar_fecha_hora_inicio_vigencia
		End Get
		Set(ByVal value As Date?)
	        Me._tar_fecha_hora_inicio_vigencia = value
		End Set
	End Property
	
	Private _tar_fecha_hora_fin_vigencia As Date? 
	Public Overridable Property Tar_fecha_hora_fin_vigencia As Date?
		Get
	        Return Me._tar_fecha_hora_fin_vigencia
		End Get
		Set(ByVal value As Date?)
	        Me._tar_fecha_hora_fin_vigencia = value
		End Set
	End Property
	
	Private _tar_observaciones As String 
	Public Overridable Property Tar_observaciones As String
		Get
	        Return Me._tar_observaciones
		End Get
		Set(ByVal value As String)
	        Me._tar_observaciones = value
		End Set
	End Property
	
	Private _tar_estado As String 
	Public Overridable Property Tar_estado As String
		Get
	        Return Me._tar_estado
		End Get
		Set(ByVal value As String)
	        Me._tar_estado = value
		End Set
	End Property
	
	Private _tar_UID_1 As Short? 
	Public Overridable Property Tar_UID_1 As Short?
		Get
	        Return Me._tar_UID_1
		End Get
		Set(ByVal value As Short?)
	        Me._tar_UID_1 = value
		End Set
	End Property
	
	Private _tar_UID_2 As Short? 
	Public Overridable Property Tar_UID_2 As Short?
		Get
	        Return Me._tar_UID_2
		End Get
		Set(ByVal value As Short?)
	        Me._tar_UID_2 = value
		End Set
	End Property
	
	Private _tar_UID_3 As Short? 
	Public Overridable Property Tar_UID_3 As Short?
		Get
	        Return Me._tar_UID_3
		End Get
		Set(ByVal value As Short?)
	        Me._tar_UID_3 = value
		End Set
	End Property
	
	Private _tar_UID_4 As Short? 
	Public Overridable Property Tar_UID_4 As Short?
		Get
	        Return Me._tar_UID_4
		End Get
		Set(ByVal value As Short?)
	        Me._tar_UID_4 = value
		End Set
	End Property
	
	Private _tar_usuario_grabacion As String 
	Public Overridable Property Tar_usuario_grabacion As String
		Get
	        Return Me._tar_usuario_grabacion
		End Get
		Set(ByVal value As String)
	        Me._tar_usuario_grabacion = value
		End Set
	End Property
	
	Private _tar_fecha_grabacion As Date? 
	Public Overridable Property Tar_fecha_grabacion As Date?
		Get
	        Return Me._tar_fecha_grabacion
		End Get
		Set(ByVal value As Date?)
	        Me._tar_fecha_grabacion = value
		End Set
	End Property
	
	Private _tar_usuario_modificacion As String 
	Public Overridable Property Tar_usuario_modificacion As String
		Get
	        Return Me._tar_usuario_modificacion
		End Get
		Set(ByVal value As String)
	        Me._tar_usuario_modificacion = value
		End Set
	End Property
	
	Private _tar_fecha_modificacion As Date? 
	Public Overridable Property Tar_fecha_modificacion As Date?
		Get
	        Return Me._tar_fecha_modificacion
		End Get
		Set(ByVal value As Date?)
	        Me._tar_fecha_modificacion = value
		End Set
	End Property
	
End Class
